AllCops:
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'config/puma.rb'
    - 'config/application.rb'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
