AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'bin/**/*'
    - 'config/initializers/*'
    - 'config/deploy/*'
    - 'config/deploy.rb'
    - 'config/puma.rb'
    - 'config/environments/production.rb'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'lib/tasks/*'
    - 'Capfile'
    - 'Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
